### ISSUE TITLE
library not found for -lPods

### ISSUE THREAD

**Issue by johnheb** [BadChoice/RVCalendarWeekView#1]
RV,  
1. Downloaded revised version
2. Installed the pod -  see listing below.
3. Build the:  RVCalendarWeekView.xcworkspace
4. ERROR  ld: library not found for -lPods

Does show in the Linked Frameworks and Libraries 

Thanks for any help you can provide.

John

**POD INSTALL:**

iMac:RVCalendarWeekView-master iMac$ pod install
Analyzing dependencies
Downloading dependencies
Installing Collection (1.3.9)
Installing DateTools (1.7.0)
Installing EasyDate (0.7)
Installing Masonry (1.0.1)
Installing UIColor-HexString (1.3.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 5 total pods installed.

**ERROR IN Building the:   RVCalendarWeekView.xcworkspace**

Ld /Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos/RVCalendarWeekView.app/RVCalendarWeekView normal arm64
    cd /Users/iMac/Desktop/RVCalendarWeekView-master
    export IPHONEOS_DEPLOYMENT_TARGET=9.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos -L/Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos/Collection -L/Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos/DateTools -L/Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos/EasyDate -L/Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos/Masonry -L/Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos/UIColor-HexString -F/Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos -filelist /Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Intermediates/RVCalendarWeekView.build/Debug-iphoneos/RVCalendarWeekView.build/Objects-normal/arm64/RVCalendarWeekView.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=9.3 -dead_strip -Xlinker -no_deduplicate -fembed-bitcode-marker -ObjC -lCollection -lDateTools -lEasyDate -lMasonry -lUIColor-HexString -framework Foundation -framework UIKit -fobjc-arc -fobjc-link-runtime -lPods -lPods-RVCalendarWeekView -Xlinker -dependency_info -Xlinker /Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Intermediates/RVCalendarWeekView.build/Debug-iphoneos/RVCalendarWeekView.build/Objects-normal/arm64/RVCalendarWeekView_dependency_info.dat -o /Users/iMac/Library/Developer/Xcode/DerivedData/RVCalendarWeekView-cnfjwuzsyzzxfaceumqcccuvxqtr/Build/Products/Debug-iphoneos/RVCalendarWeekView.app/RVCalendarWeekView

ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by BadChoice** [comment]
Are you opening the workspace instead of the .xcodeproj right?

**Comment by liuliangju** [comment]
@BadChoice  open RVCalendarWeekView.xcworkspace

**Comment by BadChoice** [comment]
@liangjuliu can you check the last commit? 
ipad2 simulator is not working yet (I'm trying to figure it out why, but others simulators should)
