### ISSUE TITLE
How can I select an event and popover its information?

### ISSUE THREAD

**Issue by ssiang1627** [BadChoice/RVCalendarWeekView#11]
How can I select an event and pop over its information?
Which function should I use ? 
Just like the onLongPressAt function, I can use it to make a new event in the viewcontroller

**Comment by BadChoice** [comment]
you should use `-(void)weekView:(id)sender eventSelected:(MSEventCell*)eventCell` and setting the delegate directly in the weekview (this doesn't use the decorators)

`_weekView.delegate = self;`

Check the example in `ViewController.m`
