### ISSUE TITLE
How to set the date of the weekView?

### ISSUE THREAD

**Issue by ssiang1627** [BadChoice/RVCalendarWeekView#13]
As the title, how can I set the date of weekView?

For example,  I want to set the weekView's date to 2017, Oct, 16 ~ 2017, Oct, 25

**Comment by BadChoice** [comment]
The easies way it to extend the responsible class for it,

Steps to do so are:
1. Create your new class extending `MSDayColumnHeader`  
2. Override the `- (void)setDay:(NSDate *)day` function and set your desired format  
3. Create your own weekView class that inherts from `MSWeekView`  
4. Override  `-(void)setupSupplementaryViewClasses` calling the `super`first and then do:

```
self.dayColumnHeaderClass           = YourNewDayColumnHeader.class;
```

Thats all, I hope it works for you
