### ISSUE TITLE
Not working after 0.5.3

### ISSUE THREAD

**Issue by sultankme** [BadChoice/RVCalendarWeekView#22]
Hey,

I'm working on a Swift 3/Xocde 8 project, and RVCalendar was working perfectly with version 0.5.2, but since it got updated to 0.5.3 Xcode won't build because of semantic issues and ARC Semantic Issues in MSDayColumnHeader, MSDraggableEvent and MSTimeRowHeader. Whats the problem here?

[screen shot 2016-12-06 at 3 25 33 pm](https://cloud.githubusercontent.com/assets/7826087/20925480/41b284f2-bbc8-11e6-948c-cde4664ee459.png)

Thank you

**Comment by BadChoice** [comment]
Looks like masonry pod is not detected, can you check if has been installed in the pods?

**Comment by sultankme** [comment]
Yes its installed

**Comment by sultankme** [comment]
I've tried creating a new project and just installing RVCalendarWeekView though cocoa pods but the project won't build. I think the problem is not with 0.5.3, its with cocoa pod new release 1.1.1

**Comment by sultankme** [comment]
Removing 'use_frameworks!' from the Podfile seem to make the project build, still can't import it.

**Comment by BadChoice** [comment]
They changed something then..
Can you try changing the imports in my project to masonry to use the angled instead of "

like this

`<masonry/masonry.h>`

**Comment by sultankme** [comment]
Still same problem
![screen shot 2016-12-07 at 8 18 55 am](https://cloud.githubusercontent.com/assets/7826087/20955648/e57ee6a6-bc55-11e6-81c0-8d17c5a48f76.png)

**Comment by sultankme** [comment]
I were able to make it work by downgrading Cocoapods to 0.39 and using 'https://github.com/CocoaPods/Old-Specs.git' as a source
