### ISSUE TITLE
How to set/choose any date?

### ISSUE THREAD

**Issue by rutmb** [BadChoice/RVCalendarWeekView#28]
Hi, BadChoice!
I have been working with your library. Thanks a lot!
How can I reload weekview? For example, I select any date, then I want to reload weekView with this date as firstDay?

**Comment by BadChoice** [comment]
Hi! i'm happy it works for you.

You can use the `scrollToXX` methods

for example

```
 [self.weekView.weekFlowLayout scrollCollectionViewToClosetSectionToTime:[NSDate date] animated:NO];
 [self.decoratedWeekView.weekFlowLayout scrollCollectionViewToClosetSectionToTime:[NSDate date] animated:NO];
```

Available methods are:

```
- (void)scrollCollectionViewToClosetSectionToCurrentTimeAnimated:(BOOL)animated;
- (void)scrollCollectionViewToClosetSectionToTime:(NSDate*)time animated:(BOOL)animated;
- (void)scrollCollectionViewToCurrentTime:(BOOL)animated;
```

Check this other issue for more info

https://github.com/BadChoice/RVCalendarWeekView/issues/27
