### ISSUE TITLE
Calendar has limit swape to change day

### ISSUE THREAD

**Issue by sonysum** [BadChoice/RVCalendarWeekView#3]
i want to swape to change day all day like ios calendar app.
thanks

**Comment by BadChoice** [comment]
Add this

```
_weekView.collectionView.pagingEnabled = YES;
```

**Comment by sonysum** [comment]
can swape but days are limit
for calendar ios unlimit swape to change days

**Comment by BadChoice** [comment]
The infinite scroll is a pending feature yet, I can change the issue title to reflect that

Enviat des del meu iPhone

El 31 ag 2016, a les 12:30, sonysum notifications@github.com va escriure:

**Comment by liuliangju** [comment]
@BadChoice  i think you can solve the issue  in combination with JTCalendar.

**Comment by BadChoice** [comment]
I adde the infnite scroll in the las commit (only forward by now) you can check it
