### ISSUE TITLE
Calendar not showing

### ISSUE THREAD

**Issue by mcontin** [BadChoice/RVCalendarWeekView#32]
Hello, I extended a UIView in the storyboard with MSWeekView but the calendar is not loading in runtime. I tried force reloading, adding events and setting the delegate.
I'm using XCode 9 and my project is in Swift 4 but that shouldn't matter as I'm using other libraries just fine.
When I capture the view hierarchy the calendar is just white.
Am I forgetting something maybe?

**Comment by mcontin** [comment]
Found the "problem": I was setting the events with .addEvent() instead of setting them like in the README.

**Comment by jsolanasl** [comment]
Hi @mcontin,
Could you please provide an example of how to create a dummy MSEvent on swift 4?
I'm stuck with the same problem: MSWeekView is just white.

Thanks!
