### ISSUE TITLE
How can I customize an extra section for use to show allday events，could give me a hand.

### ISSUE THREAD

**Issue by liuliangju** [BadChoice/RVCalendarWeekView#4]

**Comment by BadChoice** [comment]
The easiest way is to just add them in the header section `MSDayColumnHeader`. You can add your views there,
However, the right way would be to create a new decorator (MSAllDayEventHeader) and modify the layout to draw them below the header.

**Comment by BadChoice** [comment]
Did it work for you?
if you do something you can do a PR so I can add it to the main

**Comment by liuliangju** [comment]
@BadChoice  Really effective，i will do a PR On the weekend

**Comment by BadChoice** [comment]
Great! Thanks!
