### ISSUE TITLE
RVCalendarWeekView not working in swift4

### ISSUE THREAD

**Issue by Naser-Mohamed** [BadChoice/RVCalendarWeekView#45]
After installing RVCalendarWeekView via pods in swift4, I got more errors i.e
- No visible @interface for 'UILabel' declares the selector 'makeConstraints:'
- Property 'right' not found on object of type 'MSDragableEvent *'
- Property 'left' not found on object of type 'MSDragableEvent *'
- Passing 'CGPoint' (aka 'struct CGPoint') to parameter of incompatible type '__strong id'
- elc

**Comment by BadChoice** [comment]
Hi,
I'm sorry but I haven't done the switch to swift yet... so I'm afraid I can't help you here...
Maybe somebody else has this error and can help us

**Comment by logicsb** [comment]
This problem is about the new version of Masonry. I'll update and send a pull request

**Comment by BadChoice** [comment]
thanks @logicsb  for the fix!

**Comment by nivritgupta** [comment]
@logicsb how you fixed this issue ?
