### ISSUE TITLE
Example not building

### ISSUE THREAD

**Issue by Abhinav93** [BadChoice/RVCalendarWeekView#5]
Example on build shows following errors:
No visible @interface for 'NSDate' declares the selector 'withMinute:' and more errors related to easy date.
Already cleared derived data for project.
Installed pods again
Still not working

**Comment by BadChoice** [comment]
It works for me, what cocoapods version do you have?

**Comment by Abhinav93** [comment]
I have version 1.0.1 and easydate version 0.3

**Comment by Abhinav93** [comment]
You can close this, the issue is fixed in latest commit.
 Great Work.
Thanks.

**Comment by BadChoice** [comment]
Thanks great!
