### ISSUE TITLE
 How to customize earliest/latest hour?  iPhone dayToShowOnScreen?

### ISSUE THREAD

**Issue by ssiang1627** [BadChoice/RVCalendarWeekView#8]
1.Can I customize  earliest/latest hour?
2.It seems that dayToShowOnScreen limits to 1 on iPhone
How can I show a week just like on iPad?
And can I make it like a weekly view( like the weekly view of Mac's Calendar)? 
It starts from Sunday to Saturday, and when I slide, It would change the whole week to the previous or next week.

I am a beginner of programming, really thanks!  
Siang

**Comment by BadChoice** [comment]
You can't customize earliest/latests hour yet
I'll check the iPhone landscape view with daysToShow to 7 when in landscape I believe I have it limited for a reason hehe

**Comment by BadChoice** [comment]
Just fixed the daysToShow in iPhone, you can set it as you want now
