### ISSUE TITLE
In example, the long pressed event will create event with a day shift

### ISSUE THREAD

**Issue by lioliajohn** [BadChoice/RVCalendarWeekView#9]
When long pressing in a day slot to create an event in example, the event will be created with correct NSDate but it shows in a day earlier.
Ex:
Long pressing on day 2016/09/09 10:00AM will create an event with right NSDate but the real event block will be shown on 2016/09/08 10:00AM.
Wonder why there is always a day offset.

![image](https://cloud.githubusercontent.com/assets/328590/18371597/7c76e4f8-75ea-11e6-99ea-67d87728db9e.png)

**Comment by BadChoice** [comment]
I believe it is due the timezone,
What timezone are you on?

**Comment by BadChoice** [comment]
I also see that the dark bacground cells are on thursday/friday instead of starudary/sunday

**Comment by lioliajohn** [comment]
Thank you so much for your quick reply! My timezone is PST. I printed out the time in UTC and PST (Please see image attached), and the cursor is where the point I long press.

![image](https://cloud.githubusercontent.com/assets/328590/18382919/f08c20b8-7637-11e6-916c-18376cf287b9.png)

As you can see, the date is all at 9/12 but it's shown the block on 9/11. I wonder if this is the problem originally from MSCollectionViewCalendarLayout.m (around Line 383 which calculate itemMinX).

Really appreciate your help!

**Comment by lioliajohn** [comment]
For dark background one, I don't change a thing on this. I suspect this but don't know why. I double checked the git folder I cloned, and I didn't see any change I made to it. Strange...

**Comment by BadChoice** [comment]
Its really weird since it works ok in mine, (I'm at utc+2) but yeah it doesn't seem a timezone issue,
so I may come from the original flow layout I forked,
I haven't messed with that code so much yet I'll take a look and see If I can find anything, or let me know if you find why we can fix it.

Thank you!

**Comment by lioliajohn** [comment]
Thank you again for the help!

I found one interesting thing. If I turned off the automatically update timezone in system preferences and changed the timezone to Taipei - Taiwan, and it worked perfectly fine! But if I set back to Cupertino - CA, then it didn't work again.

I will dig into it more in MSCollectionViewCalendarLayout.m later. :)

**Comment by BadChoice** [comment]
Well this says it a timezone issue hehe

**Comment by BadChoice** [comment]
Or maybe it is the first day of week, can you try to set firstday of week as the one you have on calendar, untill sunday and saturday are greyed out so se can see if it is that

**Comment by BadChoice** [comment]
@ivyliolia Did you find anything about it?

**Comment by BadChoice** [comment]
This is fixed in the last commits ;)
